#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
Mod=Mod1    # Use alt as the main modifier
#Mod=Mod4   # Use the super key as the main modifier


#scripts
hc spawn /home/notis/.config/herbstluftwm/lasttag.sh
hc keybind $Mod-semicolon spawn /home/notis/.config/herbstluftwm/swap.sh auto
hc keybind $Mod-slash spawn /home/notis/.config/herbstluftwm/swap.sh close
hc keybind $Mod-minus spawn /home/notis/.config/herbstluftwm/scratchpad.sh
hc keybind $Mod-m spawn /home/notis/.config/herbstluftwm/maximize.sh
#hc keybind $Mod-w spawn /home/notis/.config/herbstluftwm/windowmenu.sh
hc keybind $Mod-Control-f spawn /home/notis/.config/herbstluftwm/fanmenu.sh
hc keybind $Mod-Control-p spawn /home/notis/.config/herbstluftwm/exitmenu.sh
hc keybind $Mod-Control-s spawn /home/notis/.config/herbstluftwm/toggledualhead.sh
hc keybind $Mod-Control-m spawn /home/notis/.config/herbstluftwm/polybarmenu.sh
hc keybind $Mod-Control-t spawn /home/notis/.config/herbstluftwm/toggle_bottom_bar.sh
hc keybind $Mod-t emit_hook goto_last_tag
hc keybind $Mod-t emit_hook goto_last_tag
#hc keybind $Mod-Control-i emit_hook list_keys
#hc keybind $Mod-Control-v emit_hook version
#hc keybind $Mod-Control-d spawn /home/notis/.config/herbstluftwm/hlwm-layout-manager.sh save
hc keybind $Mod-Control-a spawn /home/notis/.config/herbstluftwm/hlwm-layout-manager.sh load
hc keybind $Mod-Control-c spawn /home/notis/.config/herbstluftwm/herstcmd.sh
hc keybind $Mod-b spawn /home/notis/.config/herbstluftwm/herstcmd.sh bring
hc keybind $Mod-j spawn rofi -show window
hc keybind $Mod-w spawn /home/notis/.config/herbstluftwm/herstcmd.sh move

#minimize
hc keybind $Mod-n       spawn /home/notis/.config/herbstluftwm/hide_window.sh +1
hc keybind $Mod-Shift-n spawn /home/notis/.config/herbstluftwm/hide_window.sh -1
hc keybind $Mod-Control-n spawn /home/notis/.config/herbstluftwm/hide_window.sh 0

hc keybind XF86AudioLowerVolume spawn amixer -q set Master 5%-
hc keybind XF86AudioRaiseVolume spawn amixer -q set Master 5%+
hc keybind XF86AudioMute spawn amixer -q set Master toggle
hc keybind XF86AudioNext spawn mpc next
hc keybind XF86AudioPrev spawn mpc prev
hc keybind XF86AudioPlay spawn mpc toggle
hc keybind XF86Mail spawn thunderbird
hc keybind XF86Music spawn st -e ncmpcpp
#hc keybind XF86Search spawn catfish
hc keybind XF86Calculator spawn galculator
hc keybind Print spawn bash -c "scrot '%Y-%m-%d_$wx$h_scrot.png' -e 'mv $f ~/Pictures/'; herbstclient emit_hook print"
hc keybind XF86HomePage spawn jgmenu_run

hc keybind $Mod-Control-q quit
hc keybind $Mod-Control-r reload
hc keybind $Mod-q close
hc keybind $Mod-Escape spawn xkill

# Run Apps
hc keybind $Mod-Return spawn st -e zsh # use your $TERMINAL with xterm as fallback
hc keybind $Mod-a spawn rofi -combi-modi window,drun -show combi -modi combi

hc keybind Mod4-f spawn firefox
hc keybind Mod4-e spawn thunderbird
hc keybind Mod4-v spawn viber
hc keybind Mod4-l spawn i3lock-fancy 
hc keybind Mod4-s spawn slack
hc keybind Mod4-d spawn subl3
hc keybind Mod4-g spawn gitkraken

# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right

# moving clients
hc keybind $Mod-Control-Left  shift left
hc keybind $Mod-Control-Down  shift down
hc keybind $Mod-Control-Up    shift up
hc keybind $Mod-Control-Right shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-u       spawn bash -c "herbstclient split   bottom  0.5"
hc keybind $Mod-o       spawn bash -c "herbstclient split   right  0.5"
hc keybind $Mod-Control-u       spawn bash -c "herbstclient split   top  0.5"
hc keybind $Mod-Control-o       spawn bash -c "herbstclient split   left  0.5"
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode
hc keybind $Mod-z rotate

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep

# Shifting to monitor
hc keybind $Mod-d shift_to_monitor 1
hc keybind $Mod-Control-d shift_to_monitor 0

# tags
tag_names=( "   " "   " "   " "   " "   " "   " "   " "   " "   " "   " "   " "   " "   " "   ")
tag_keys=( {1..14} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] && [ $key -lt 11 ]; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Control-$key" move_index "$i"
    else
        if [ $key -eq 11 ];then
            hc keybind "Mod4-1" use_index 10
            hc keybind "Mod4-Control-1" move_index 10
        elif [ $key -eq 12 ];then
            hc keybind "Mod4-2" use_index 11
            hc keybind "Mod4-Control-2" move_index 11
        elif [ $key -eq 13 ];then
            hc keybind "Mod4-3" use_index 12
            hc keybind "Mod4-Control-3" move_index 12
        elif [ $key -eq 14 ];then
            hc keybind "Mod4-4" use_index 13
            hc keybind "Mod4-Control-4" move_index 13
        fi
    fi
done
hc keybind "$Mod-0" use_index 9
hc keybind "$Mod-Control-0" move_index 9

herbstclient pad 0 24 0 0

# cycle through tags
hc keybind Mod4-period use_index +1 --skip-visible
hc keybind Mod4-comma  use_index -1 --skip-visible
hc keybind $Mod-period spawn /home/notis/.config/herbstluftwm/herbst-move.py +1 full
hc keybind $Mod-comma  spawn /home/notis/.config/herbstluftwm/herbst-move.py -1 full

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s spawn bash -c "herbstclient floating toggle; herbstclient emit_hook floating"
hc keybind $Mod-x spawn bash -c "herbstclient pseudotile toggle; herbstclient emit_hook pseudotile"
hc keybind $Mod-f spawn bash -c "herbstclient fullscreen toggle; herbstclient emit_hook fullscreen"
hc keybind $Mod-Shift-f substitute FSRESTORE clients.focus.fullscreen chain , fullscreen on , attr clients.focus.ewmhnotify toggle , spawn herbstclient fullscreen FSRESTORE

#hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

hc keybind $Mod-g set_layout grid

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222'
hc set frame_border_normal_color '#101010'
hc set frame_bg_normal_color '#565656'
hc set frame_bg_active_color '#345F0C'
hc set frame_border_width 0
hc set always_show_frame 1
hc set frame_bg_transparent 0
hc set frame_active_opacity 40
hc set frame_normal_opacity 40
hc set frame_transparent_width 0
hc set frame_gap 8
hc set focus_follows_mouse 1
hc set default_frame_layout grid

hc attr theme.active.color '#9fbc00'
hc attr theme.normal.color '#454545'
hc attr theme.urgent.color orange
hc attr theme.inner_width 1
hc attr theme.inner_color black
hc attr theme.border_width 1
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#3E4A00'
hc attr theme.active.outer_color '#3E4A00'

hc attr theme.minimal.color '#9fbc00'
hc attr theme.minimal.active.color '#9fbc00'
hc attr theme.minimal.normal.color '#454545'
hc attr theme.minimal.border_width 4
hc attr theme.minimal.outer_width 1
hc attr theme.minimal.outer_color black 
hc attr theme.tiling.border_width 4
hc attr theme.tiling.outer_width 1
hc attr theme.tiling.outer_color black


hc attr theme.background_color '#141414'

hc set window_gap 5
hc set frame_padding 0
hc set smart_window_surroundings 1
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
# rules
hc unrule -F
hc rule class=Termite tag="   " hook="   " focus=off
hc rule class=St tag="   " hook="   " focus=off
hc rule class=XTerm tag="   " hook="   " focus=off
hc rule class=firefox tag="   " hook="   " focus=off ewmhrequests=off
hc rule class=Thunderbird tag="   " hook="   " focus=off
hc rule class=Google-chrome tag="   "
hc rule class=Pcmanfm tag="   " hook="   " focus=off
hc rule class=Polo-gtk tag="   " 
hc rule class=Corebird tag="   " hook="   " focus=off 
hc rule class=Pidgin tag="   " hook="   " focus=off
hc rule class=Hexchat tag="   " hook="   " focus=off
hc rule instance=Viber tag="   " pseudotile=on hook="   " focus=off 
hc rule class=Slack tag="   " pseudotile=on hook="   " focus=off
hc rule class=Clementine tag="   "
hc rule class=Mpv tag="   "
hc rule class=vlc tag="   " hook="   " focus=off
hc rule class=Popcorn-Time tag="   "  hook="   " focus=off
hc rule class=Spotify tag="   " 
hc rule class=Chromium-browser tag="   "
hc rule class=GitKraken tag="   " hook="   " focus=off pseudotile=on
hc rule class=Atom tag="   " hook="   "
hc rule class=Subl3 tag="   " hook="   "
hc rule class=QtCreator tag="   " hook="   "
hc rule class=Code tag="   " hook="   "
hc rule class=Gvim tag="   " hook="   "
hc rule class=org.remmina.Remmina tag="   " hook="   "
hc rule class=Filezilla tag="   " hook="   "
hc rule class=DesktopEditors tag="   " hook="   "
hc rule instance=FoxitReader tag="   " hook="   "
hc rule class=Zathura tag="   " hook="   "
hc rule class=Sxiv tag="   " hook="   "
hc rule class=Gimp-2.10 tag="   " hook="   "
hc rule class=Pencil tag="   " hook="   "

hc rule class=Arandr tag="   " hook="   "
hc rule class=Xfce4-power-manager-settings tag="   " pseudotile=off hook="   "
hc rule class=gufw.py tag="   " hook="   "
 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=Gsimplecal manage=off 

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

#autostart]
herbstclient emit_hook quit_panel
pid=( )
sleep 1
dunst -conf /home/notis/.config/dunst/dunstrc &
feh --bg-scale /home/notis/Pictures/fineas-anton-_q5H19c-VwU-unsplash.jpg

# find the panel
panel=~/.config/herbstluftwm/panel_polybar.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel_polybar.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
    if [ $monitor -eq 0 ]; then
        rm /tmp/my-awesome-polybar1.pid
        rm /tmp/bottom-bar.pid
        sleep 1
        polybar my-awesome-polybar1 &
        pids+=( $! )
        echo "$!" > /tmp/my-awesome-polybar1.pid
        polybar bottom-bar &
        pids+=( $! )
        echo "$!" > /tmp/bottom-bar.pid
        hc spawn polybar my-awesome-polybar0
        
    else
        hc spawn polybar my-awesome-polybar0
    fi

    #sed -i s/^RUNS.*/RUNS=0/ $0
done

herbstclient -w '(quit_panel|reload)'

kill ${pids[@]}
