#! /bin/sh
polybar-msg cmd quit
sxhkd &
polybar bspwm-polybar&
pids+=( $! )
echo "$!" > /tmp/bspwm-polybar.pid
polybar bottom-bar&
pids+=( $! )
echo "$!" > /tmp/bottom-bar.pid
feh --bg-scale /home/notis/Pictures/randy-tarampi-a5KMylND9Bo-unsplash.jpg&
compton -b&

bspc monitor HDMI1 -d term www file chat media code git docs sys
bspc monitor -g 2560x1080+0+0

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color '#ffb52a'

bspc rule -a Gimp desktop='^8' state=floating follow=off
bspc rule -a firefox desktop='^2'
bspc rule -a St desktop='^1'
bspc rule -a Pcmanfm desktop='^3'
bspc rule -a Subl3 desktop='^6'
bspc rule -a Mpv desktop='^5'
bspc rule -a vlc desktop='^5'
bspc rule -a Popcorn-Time='^5'
bspc rule -a Cawbird desktop='^4'
bspc rule -a Viber desktop='^4'
bspc rule -a GitKraken desktop='^7'
bspc rule -a Pcmanfm desktop='^3'
bspc rule -a Sxiv desktop='^8'
bspc rule -a Zathura desktop='^8'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
#[ -e "$PANEL_FIFO" ] && bspc subscribe report > "$PANEL_FIFO" &
#pgrep -x panel > /dev/null || panel &
