#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< "Lock|Suspend|Reboot|Shutdown")"
            case "$MENU" in
                *Lock) i3lock-fancy ;;
                *Suspend) systemctl suspend ;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
